# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fastest"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enable entities light source.
	entities = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				zoglin = true
				egg = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				wither_skull = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				block_display = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				wither_skeleton = true
				salmon = true
				wandering_trader = true
				vex = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				ominous_item_spawner = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.rpg-minibosses]
				trickster = true
				templar = true
				mercenary = true
				archmage_fire = true
				juggernaut = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.spell_engine]
				spell_projectile = true
				spell_area_effect = true

			[light_sources.settings.entities.witcher_rpg]
				yrden_magical_trap = true
				yrden = true

			[light_sources.settings.entities.xtraarrows]
				diamond_magnetic_arrow = true
				iron_arrow = true
				diamond_torch_arrow = true
				iron_lightning_arrow = true
				flint_atlantean_arrow = true
				golden_life_steal_arrow = true
				iron_soul_torch_arrow = true
				flint_slime_arrow = true
				flint_tracking_arrow = true
				golden_magnetic_arrow = true
				iron_magnetic_arrow = true
				golden_arrow = true
				netherite_atlantean_arrow = true
				iron_lantern_arrow = true
				netherite_arrow = true
				diamond_ender_arrow = true
				golden_explosive_arrow = true
				iron_gravity_arrow = true
				netherite_slime_arrow = true
				padded_arrow = true
				golden_soul_lantern_arrow = true
				golden_soul_torch_arrow = true
				netherite_lantern_arrow = true
				diamond_arrow = true
				golden_redstone_torch_arrow = true
				diamond_gravity_arrow = true
				flint_ender_arrow = true
				netherite_freezing_arrow = true
				breeding_arrow = true
				golden_apple_arrow = true
				netherite_lightning_arrow = true
				iron_soul_lantern_arrow = true
				diamond_tracking_arrow = true
				netherite_redstone_torch_arrow = true
				diamond_life_steal_arrow = true
				iron_torch_arrow = true
				iron_ender_arrow = true
				flint_soul_torch_arrow = true
				iron_vexing_arrow = true
				incendiary_arrow = true
				cupids_arrow = true
				diamond_lightning_arrow = true
				diamond_explosive_arrow = true
				netherite_explosive_arrow = true
				flint_magnetic_arrow = true
				flint_torch_arrow = true
				iron_atlantean_arrow = true
				flint_lantern_arrow = true
				flint_soul_lantern_arrow = true
				golden_ender_arrow = true
				flint_life_steal_arrow = true
				golden_lightning_arrow = true
				netherite_gravity_arrow = true
				diamond_lantern_arrow = true
				diamond_soul_lantern_arrow = true
				netherite_life_steal_arrow = true
				diamond_vexing_arrow = true
				iron_freezing_arrow = true
				diamond_freezing_arrow = true
				diamond_atlantean_arrow = true
				golden_freezing_arrow = true
				golden_gravity_arrow = true
				iron_slime_arrow = true
				golden_vexing_arrow = true
				netherite_torch_arrow = true
				flint_vexing_arrow = true
				apple_arrow = true
				iron_explosive_arrow = true
				netherite_vexing_arrow = true
				notch_apple_arrow = true
				golden_torch_arrow = true
				iron_tracking_arrow = true
				diamond_soul_torch_arrow = true
				netherite_soul_torch_arrow = true
				golden_lantern_arrow = true
				golden_slime_arrow = true
				flint_lightning_arrow = true
				iron_life_steal_arrow = true
				diamond_slime_arrow = true
				flint_explosive_arrow = true
				flint_redstone_torch_arrow = true
				flint_gravity_arrow = true
				headless_arrow = true
				golden_tracking_arrow = true
				netherite_soul_lantern_arrow = true
				leashing_arrow = true
				flint_freezing_arrow = true
				golden_atlantean_arrow = true
				diamond_redstone_torch_arrow = true
				extinguishing_arrow = true
				iron_redstone_torch_arrow = true
				netherite_tracking_arrow = true
				netherite_magnetic_arrow = true
				netherite_ender_arrow = true

			[light_sources.settings.entities.regions_unexplored]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.too_many_bows]
				vitality_arrow = true
				ancient_sage_arrow = true
				cursed_flame_arrow = true
				webstring_arrow = true
				aurora_arrow = true
				rift_entity = true
				hunter_arrow = true
				astral_arrow = true
				tidal_arrow = true
				ironclad_arrow = true
				shulker_blast_projectile = true
				venom_arrow = true
				flame_arrow = true
				wind_projectile = true
				icicle_javelin = true
				torchbearer_arrow = true
				sentinel_arrow = true
				frostbite_arrow = true
				sonic_boom_projectile = true
				dusk_reaper_arrow = true
				lightning_arrow = true
				hunter_xp_arrow = true
				radiant_arrow = true
				spectral_arrow = true
				dragons_breath_arrow = true

			[light_sources.settings.entities.knightquest]
				ratman = true
				bad_patch = true
				ghastling = true
				netherman_clone = true
				eldknight = true
				fallen_knight = true
				eldbomb = true
				netherman = true
				netherman_projectile_charge = true
				gremlin = true
				swampman_axe = true
				ghosty = true
				swampman = true
				samhain = true
				lizzy = true

			[light_sources.settings.entities.mobs_of_mythology]
				kobold_warrior = true
				automaton = true
				sporeling = true
				kobold = true
				drake = true
				chupacabra = true
				basilisk = true
				pegasus = true

			[light_sources.settings.entities.variantsandventures]
				verdant = true
				gelid = true
				murk = true
				thicket = true

			[light_sources.settings.entities.illagerinvasion]
				skull_bolt = true
				sorcerer = true
				alchemist = true
				surrendered = true
				necromancer = true
				basher = true
				firecaller = true
				invoker = true
				marauder = true
				invoker_fangs = true
				flying_magma = true
				hatchet = true
				provoker = true
				archivist = true
				inquisitor = true

			[light_sources.settings.entities.biomeswevegone]
				pumpkin_warden = true
				oddion = true
				man_o_war = true
				chest_boat = true
				boat = true

			[light_sources.settings.entities.goblintraders]
				vein_goblin_trader = true
				goblin_trader = true

			[light_sources.settings.entities.adventurez]
				deer = true
				skeleton_vanguard = true
				thrown_rock = true
				desert_rhino = true
				piglin_beast = true
				blaze_guardian = true
				ender_whale = true
				shaman = true
				dragon = true
				iguana = true
				amethyst_golem = true
				soul_reaper = true
				red_fungus = true
				void_cloud = true
				summoner = true
				void_bullet = true
				orc = true
				the_eye = true
				necromancer = true
				fire_breath = true
				void_fragment = true
				brown_fungus = true
				blaze_guardian_shield = true
				blackstone_golem = true
				nightmare = true
				mini_blackstone_golem = true
				mammoth = true
				void_shade = true
				tiny_eye = true
				wither_puppet = true
				enderwarthog = true
				void_shadow = true
				amethyst_shard = true
				gilded_blackstone_shard = true

			[light_sources.settings.entities.frostiful]
				glacial_arrow = true
				frost_spell = true
				packed_snowball = true
				biter = true
				freezing_wind = true
				chillager = true
				frostologer = true
				thrown_icicle = true

			[light_sources.settings.entities.brutalbosses]
				thrownitem = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.paladins]
				battle_banner = true
				barrier = true

			[light_sources.settings.entities.elemental_wizards_rpg]
				dripstone_small = true
				dripstone_big = true
				tornado = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.snuffles]
				snuffle = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				sludge = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				boat = true
				angler_fish = true
				sculk_snapper = true

			[light_sources.settings.entities.takesapillage]
				archer = true
				skirmisher = true
				clay_golem = true
				legioner = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.oblivion]
				elk = true
				piranha = true
				elysian_shaman = true
				horned_sheep = true
				treeder = true
				boar = true
				turkey = true
				wooly_cow = true
				shlama = true
				elysian_wolf = true
				goblin = true
				shroom = true
				elysian_elk = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				lich = true
				blue_fireball = true
				spore_ball = true
				obsidilith = true
				petal_blade = true
				charged_ender_pearl = true
				comet = true
				gauntlet = true
				soul_star = true
				void_blossom = true

			[light_sources.settings.entities.hexblade]
				magus = true
				magister = true
				hexbladeportal = true

			[light_sources.settings.entities.the_bumblezone]
				pollen_puff = true
				thrown_stinger_spear = true
				cosmic_crystal_entity = true
				bee_queen = true
				purple_spike_entity = true
				honey_crystal_shard = true
				beehemoth = true
				electric_ring_entity = true
				honey_slime = true
				rootmin = true
				variant_bee = true
				dirt_pellet = true
				bee_stinger = true
				sentry_watcher = true

			[light_sources.settings.entities.spellbladenext]
				cycloneentity = true

			[light_sources.settings.entities.formidulus]
				deer_follower = true
				irrlicht = true
				deer_god = true
				pumpkin = true
				bulwark = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.supplementaries]
				falling_ash = true

			[light_sources.settings.entities.eternal_starlight]
				sonar_bomb = true
				energized_flame = true
				frozen_tube = true
				thirst_walker = true
				starlight_golem = true
				grimstone_golem = true
				shattered_blade = true
				gleech = true
				gatekeeper_fireball = true
				lunar_thorn = true
				freeze = true
				twilight_gaze = true
				crest = true
				lunar_monstrosity = true
				frozen_bomb = true
				chain_of_souls = true
				aurora_deer = true
				luminofish = true
				lunar_spore = true
				tiny_creteor = true
				boarwarf = true
				air_sac_arrow = true
				tower_squid = true
				yeti = true
				shadow_snail = true
				creteor = true
				crystallized_moth = true
				tangled_skull = true
				eye_of_seeking = true
				amaramber_arrow = true
				lonestar_skeleton = true
				tangled_hatred = true
				aethersent_meteor = true
				the_gatekeeper = true
				ratlin = true
				ashen_snowball = true
				lunar_monstrosity_breath = true
				gleech_egg = true
				wilted_petal = true
				tangled_hatred_part = true
				nightfall_spider = true
				ent = true
				chest_boat = true
				soulit_spectator = true
				aetherstrike_rocket = true
				boat = true
				falling_block = true
				tangled = true
				astral_golem = true
				shimmer_lacewing = true
				painting = true
				voracious_arrow = true
				golem_laser_beam = true
				luminaris = true

			[light_sources.settings.entities.medievalorigins]
				summon_zombie = true
				summon_wither_skeleton = true
				summon_skeleton = true
				summoned_arrow = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				player_illusion = true
				ice_chunk = true
				moobloom = true
				tuff_golem = true
				mauler = true
				iceologer = true
				wildfire = true
				crab = true
				rascal = true

			[light_sources.settings.entities.growsseth]
				researcher = true

			[light_sources.settings.entities.mythicmetals]
				banglum_tnt_minecart = true
				star_platinum_arrow = true
				runite_arrow = true
				banglum_tnt = true
				banglum_nuke = true
				palladium_minecart = true

			[light_sources.settings.entities.cardiac]
				life_orb = true
				thrown_life_bottle = true

			[light_sources.settings.entities.affinity]
				wise_wisp = true
				vicious_wisp = true
				aethum_missile = true
				emancipated_block = true
				inert_wisp = true
				asteroid = true
