[general]
lunarEventChance = 0.2
[events]
bloodMoonWeight = 40
crimsonMoonWeight = 20
minerMoonWeight = 40
whiteMoonWeight = 10
tinyMoonWeight = 0
bigMoonWeight = 0
badOmenMoonWeight = 5
heroMoonWeight = 0
eclipseMoonWeight = 0
[crimson]
crimsonReplacements = ["minecraft:zombie,minecraft:zombified_piglin", "minecraft:husk,minecraft:zombified_piglin", "minecraft:drowned,minecraft:zombified_piglin", "minecraft:skeleton,minecraft:wither_skeleton", "minecraft:slime,minecraft:magma_cube", "minecraft:spider,minecraft:zoglin"]
