# Don't change this! Version used to track needed updates.
version = 0
# Disables the client side auto swap feature for all connected clients.
disable_auto_swap = false
# Spells should cost health. Set to `false` to remove health cost from all spells.
spell_cost_health_allowed = false
# Spells should cost mana. Set to `false` to remove mana cost from all spells.
spell_cost_mana_allowed = false
# Spells should cost stamina. Set to `false` to remove stamina cost from all spells.
spell_cost_stamina_allowed = false
# Spells should require and optionally remove status effects. Set to `false` to remove effect cost from all spells.
spell_cost_effects_allowed = true
# Spells can be affected by the 'generic.extra_launch_count' entity attribute
spell_launch_properties_extra_launch_count_attribute_allowed = true
# Spells can be affected by the 'generic.extra_launch_delay' entity attribute
spell_launch_properties_extra_launch_delay_attribute_allowed = true
# Spells can be affected by the 'generic.extra_velocity' entity attribute
spell_launch_properties_extra_velocity_attribute_allowed = true
# Spells can be affected by the 'generic.extra_ricochet' entity attribute
spell_projectile_perk_extra_ricochet_attribute_allowed = true
# Spells can be affected by the 'generic.extra_ricochet_range' entity attribute
spell_projectile_perk_extra_ricochet_range_attribute_allowed = true
# Spells can be affected by the 'generic.extra_bounce' entity attribute
spell_projectile_perk_extra_bounce_attribute_allowed = true
# Spells can be affected by the 'generic.extra_pierce' entity attribute
spell_projectile_perk_extra_pierce_attribute_allowed = true
# Spells can be affected by the 'generic.extra_chain_reaction_size' entity attribute
spell_projectile_perk_extra_chain_reaction_size_attribute_allowed = true
# Spells can be affected by the 'generic.extra_chain_reaction_triggers' entity attribute
spell_projectile_perk_extra_chain_reaction_triggers_attribute_allowed = true